In [1]:
import torch

C:\Users\acer.DESKTOP-B6RLPDD.000\AppData\Local\Programs\Python\Python39\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
from .autonotebook import tqdm as notebook_tqdm

In [2]:
# scalar value
x=torch.empty(1)
print(x)

tensor([0.])


In [3]:
# print a 1D vector
x=torch.empty(3)
print(x)

tensor([0., 0., 0.])


In [8]:
# create a matix
x=torch.empty(2,3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 1.8754e+28],
        [6.3455e-10, 3.3614e+21, 1.0084e-11]])


In [4]:
# create a 3d
x=torch.empty(2,3,5)
print(x)

tensor([[[0.0000e+00, 0.0000e+00, 1.4013e-45, 0.0000e+00, 1.4013e-45],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 1.4013e-45, 0.0000e+00, 9.1841e-41, 9.2761e-39]]])


In [ ]:
# create a 4d
x=torch.empty(2,3,5,7)
print(x)

: 

In [6]:
# get random values
# create a 2d
x=torch.rand(2,5)
print(x)

tensor([[0.9404, 0.1500, 0.7835, 0.7591, 0.6916],
        [0.8209, 0.9166, 0.5585, 0.9169, 0.8574]])


In [7]:
# make a matrix with zeros in it
x=torch.zeros(4,5)
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [8]:
# get ones in all the items
x=torch.ones(2,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# check the datatype
x.dtype

torch.float32

In [10]:
# we can also the datatype while declaring
x=torch.empty(2,3,dtype=torch.int)
x
# we can have int,double or float with size 15,32

tensor([[   0,    1,    0],
        [   0, 1080,    0]], dtype=torch.int32)

In [11]:
# print the size
x.size()

torch.Size([2, 3])

In [12]:
# we can also contruct a tensor from data, like from a list
x=torch.tensor([4,5,3,2])
x

tensor([4, 5, 3, 2])

let's talk about some basic operations we can do 

In [13]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x)
print(y)
# z=x+y element wise addition
z=torch.add(x,y)
print(z)

tensor([[0.7853, 0.3093],
        [0.8186, 0.8290]])
tensor([[0.1838, 0.1335],
        [0.7622, 0.0850]])
tensor([[0.9691, 0.4428],
        [1.5808, 0.9140]])


In [14]:
# we can also do an inplace addition, for example
print("y earlier: ",y)
y.add_(x)
# this will modify the value of y
print("y now: ")
print(y)
# every function that has an underscore will do an inplace operation

y earlier:  tensor([[0.1838, 0.1335],
        [0.7622, 0.0850]])
y now: 
tensor([[0.9691, 0.4428],
        [1.5808, 0.9140]])


In [15]:
z=x*y
p=x/y
q=x-y
print(z,"\n",p,"\n",q)

tensor([[0.7610, 0.1370],
        [1.2941, 0.7577]]) 
 tensor([[0.8103, 0.6985],
        [0.5178, 0.9070]]) 
 tensor([[-0.1838, -0.1335],
        [-0.7622, -0.0850]])


In [16]:
# we can also do python operation
x=torch.rand(5,3)
print(x)
print(x[1,:]) # row 1 and all columns
print(x[1:3,:]) # row 1,2 and all columns

tensor([[0.0896, 0.9337, 0.2661],
        [0.8790, 0.0403, 0.9008],
        [0.5350, 0.9383, 0.7009],
        [0.2167, 0.2382, 0.6445],
        [0.7989, 0.1377, 0.9253]])
tensor([0.8790, 0.0403, 0.9008])
tensor([[0.8790, 0.0403, 0.9008],
        [0.5350, 0.9383, 0.7009]])


In [17]:
print(x[1,1].item())

0.040304481983184814


In [18]:
# reshaping our tensor
x=torch.rand(4,4)
print(x)
y=x.view(16) # we can a 1d array, no of elements is same
print(y)
# so we know only the no of columns, then we can put -1 in place of number of row
y=x.view(-1,8)# this will create a 2 dimensional array
print(y)

tensor([[0.9812, 0.0809, 0.2790, 0.3627],
        [0.3423, 0.5013, 0.2876, 0.5063],
        [0.8634, 0.5498, 0.7445, 0.1467],
        [0.5731, 0.5881, 0.6262, 0.5280]])
tensor([0.9812, 0.0809, 0.2790, 0.3627, 0.3423, 0.5013, 0.2876, 0.5063, 0.8634,
        0.5498, 0.7445, 0.1467, 0.5731, 0.5881, 0.6262, 0.5280])
tensor([[0.9812, 0.0809, 0.2790, 0.3627, 0.3423, 0.5013, 0.2876, 0.5063],
        [0.8634, 0.5498, 0.7445, 0.1467, 0.5731, 0.5881, 0.6262, 0.5280]])


In [34]:
print(y.size())

torch.Size([2, 8])


In [19]:
# converting from numpy array to torch tensor
import numpy as np
a=torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [20]:
# now we can convert a to numpy array
b=a.numpy()
print(b)
print(type(b))


[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [21]:
a.add_(1)
# if change the value of a now, b value will change too because they are sharing the same memory location
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [43]:
# to convert numpy to torch
a=np.ones(5)
print(a)
b=torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [22]:
if torch.cuda.is_available():
    print("yes")
else:
    print("no")

no


In [23]:
# this tells pytorch that it will need to find the gradient later of this variable
x=torch.ones(5,requires_grad=True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)