In [19]:
import torch

In [20]:
x=torch.randn(3,requires_grad=True) # by default this is false
print(x)
# so w
# henever we do any sort of computations, pytorch will create a computational graph for us

tensor([-0.4029,  0.4758, -0.6057], requires_grad=True)


In [21]:
y=x+2
# just like the back propagation

since, we specified that it requires a gradient, pytorch will automatically create a function for us and this 
will be used for create gradient

In [22]:
print(y)
# pytorch created a AddBackward0 function

tensor([1.5971, 2.4758, 1.3943], grad_fn=<AddBackward0>)


In [23]:
z=y*y*2
print(z)
# pytorch created a MulBackward0 function

tensor([ 5.1016, 12.2595,  3.8882], grad_fn=<MulBackward0>)


In [24]:
# so whatever we are doing, pytorch is creating a backward function related to it
z=z.mean()
print(z)

tensor(7.0831, grad_fn=<MeanBackward0>)


In [25]:
z.backward() 
print(x.grad)

tensor([2.1295, 3.3011, 1.8591])


In [26]:
v=torch.tensor([.1,1.0,0.001],dtype=torch.float64)

In [27]:
x=torch.randn(3,requires_grad=True)
x

tensor([-0.8019, -0.2488, -0.6465], requires_grad=True)

In [28]:
# now we want to know to prevent it from tracking the gradient, we have three option
# first to call requires_grad function and set it to false
#x.requires_grad(False)
# second is to call x.detach, this will create a new tensor that will not require the gradient
# x.detach()
# third with torch.no_grad()
# x.no_grad()

In [38]:
x.requires_grad_(False)
print(x)
print("now, we can see that it doesn't have the requirs grad option")

tensor([ 0.5243, -0.3822, -0.4152])
now, we can see that it doesn't have the requirs grad option


In [30]:
x=torch.randn(3,requires_grad=True)
print(x)
y=x.detach()
print(y)
print("it has created a vector y which doesn't need have requires grad")

tensor([ 1.0396, -0.3481, -0.6999], requires_grad=True)
tensor([ 1.0396, -0.3481, -0.6999])
it has created a vector y which doesn't need have requires grad


In [31]:
x=torch.randn(3,requires_grad=True)
with torch.no_grad():
    y=x-1+1
    print(y)

tensor([ 0.5243, -0.3822, -0.4152])


In [40]:
# whenever we call the backward function, then the gradient for this tensor will be accumulated into the .grad attribute
# that is, the values will be summed up
# let's have a training example
weights=torch.ones(4,requires_grad=True)
print(weights)
for epoch in range(1):
    model_output=(weights*3).sum()
    print(model_output)
    model_output.backward()
    print(model_output)
    print(weights)
    print(weights.grad)

tensor([1., 1., 1., 1.], requires_grad=True)
tensor(12., grad_fn=<SumBackward0>)
tensor(12., grad_fn=<SumBackward0>)
tensor([1., 1., 1., 1.], requires_grad=True)
tensor([3., 3., 3., 3.])


In [41]:
# now if we do another iteration
for epoch in range(1):
    model_output=(weights*3).sum()

    model_output.backward()
    print(model_output)
    print(weights.grad)

tensor(12., grad_fn=<SumBackward0>)
tensor([6., 6., 6., 6.])


In [34]:
# do third iteration
for epoch in range(1):
    model_output=(weights*3).sum()

    model_output.backward()

    print(weights.grad)

tensor([9., 9., 9., 9.])


In [35]:
weights=torch.ones(4,requires_grad=True)
for epoch in range(3):
    model_output=(weights*3).sum()

    model_output.backward()

    print(weights.grad)
print("this is obviously wrong here")

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])
this is obviously wrong here


In [36]:
weights=torch.ones(4,requires_grad=True)
for epoch in range(3):
    model_output=(weights*3).sum()

    model_output.backward()

    print(weights.grad)

    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [37]:
# later we will word on torch optimizer, let's use ones of them
weights=torch.ones(4,requires_grad=True)
optimizer=torch.optim.SGD([weights],lr=0.01)
optimizer.step()
optimizer.zero_grad()
print(optimizer)


SGD (
Parameter Group 0
    dampening: 0
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)
