In [1]:
import torch
import torchvision
from torch.utils.data import Dataset,DataLoader
import numpy as np

In [2]:
#dataset = torchvision.datasets.MNIST(root='./',transform=torchvision.transforms.ToTensor(),download=True)
# tranform convert the images our numpy arrays to tensors

In [3]:
class WineDataset(Dataset):
    def __init__(self,transform=None):
        # data loading
        xy=np.loadtxt('wine.csv',delimiter=",",dtype=np.float32,skiprows=1)# skiprows is 1 because we want to skip our head

        # here we didn't convert it to tensor
        self.x=xy[:,1:]# we want all the samples, but in columns, skip the first one
        self.y=xy[:,[0]] # all the samples and the first column

        self.n_samples=xy.shape[0]
        self.transform=transform

    def __getitem__(self, index):
        # allow us for inxexing later
        # dataset[0]
        sample = self.x[index],self.y[index]
        if self.transform:
            sample=self.transform(sample)
        return sample

    def __len__(self):
        # len(dataset)
        return self.n_samples

    

In [4]:
class ToTensor:
    # Convert ndarrays to Tensors
    def __call__(self, sample):
        inputs, targets = sample
        return torch.from_numpy(inputs), torch.from_numpy(targets)

In [5]:
class MulTransform:
    def __init__(self, factor):
        self.factor = factor

    def __call__(self, sample):
        inputs, targets = sample
        inputs *= self.factor
        return inputs, targets


In [6]:
dataset=WineDataset(transform=ToTensor())
# if we pass ToTensor(), then it transform to tensor, but if we pass none, then there would be no transform
first_data=dataset[0]
features,labels = first_data
print(features)
print(type(features),type(labels))

tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03])
<class 'torch.Tensor'> <class 'torch.Tensor'>


In [8]:
composed=torchvision.transforms.Compose([ToTensor(),MulTransform(4)])
dataset=WineDataset(transform=composed)
first_data=dataset[0]
features,labels = first_data
print(features)
print(labels)
print(type(features),type(labels))

tensor([5.6920e+01, 6.8400e+00, 9.7200e+00, 6.2400e+01, 5.0800e+02, 1.1200e+01,
        1.2240e+01, 1.1200e+00, 9.1600e+00, 2.2560e+01, 4.1600e+00, 1.5680e+01,
        4.2600e+03])
tensor([1.])
<class 'torch.Tensor'> <class 'torch.Tensor'>
